# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[5, 8],
       [9, 5],
       [4, 2]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [6]:
arr.reshape(1,6)

array([[5, 8, 9, 5, 4, 2]])

In [7]:
arr.ndim

2

# MAX Y ARGMAX

In [8]:
arr = np.random.randint(1,20,10)
arr

array([14, 11,  5,  6,  4, 12, 11, 15, 17,  5])

In [9]:
matriz = arr.reshape(2,5)
matriz

array([[14, 11,  5,  6,  4],
       [12, 11, 15, 17,  5]])

In [10]:
arr.max()

np.int64(17)

In [11]:
matriz.max()

np.int64(17)

In [12]:
arr.argmax()

np.int64(8)

In [13]:
matriz.argmax()

np.int64(8)

# MIN Y ARGMIN

In [14]:
arr.min()

np.int64(4)

In [15]:
matriz.min()

np.int64(4)

In [16]:
matriz.min(0)

array([12, 11,  5,  6,  4])

In [17]:
matriz.min(1)

array([4, 5])

# SORT

In [18]:
arr

array([14, 11,  5,  6,  4, 12, 11, 15, 17,  5])

In [19]:
arr.sort()
arr

array([ 4,  5,  5,  6, 11, 11, 12, 14, 15, 17])

In [20]:
arr2 = arr[::-1]
arr2

array([17, 15, 14, 12, 11, 11,  6,  5,  5,  4])