# FILTRADO DE DATOS EN NUMPY

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int64')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# SLICING

In [3]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [4]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[-1]

np.int64(10)

# CONDICIONALES

In [7]:
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
arr[condicion]

array([ 6,  7,  8,  9, 10])

In [9]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [10]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

In [11]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99])

In [12]:
arr = np.linspace(1,10,10,dtype='int64')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# copy

In [13]:
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# FILTROS POR AXIS(EJE)
## AXIS = 0 : COLUMNAS
## AXIS = 1 : FILAS

In [16]:
matriz = np.arange(1,21).reshape(5,4)
matriz

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# SUMATORIA POR FILAS

In [17]:
suma_filas = np.sum(matriz,axis=1)
suma_filas

array([10, 26, 42, 58, 74])

In [18]:
suma_columnas = np.sum(matriz,axis=0)
suma_columnas

array([45, 50, 55, 60])