In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr2 = arr.copy()
print(arr,arr2)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


# OPERACIONES ARITMETICAS CON UNA MATRIZ

In [3]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
1 / arr

/tmp/ipykernel_16147/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

# OPERACIONES CON MATRICES

In [8]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
print(matriz)
print(matriz2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [10]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# TRANSPUESTA

In [11]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])